openmrs/openmrs-esm-login

- package.json
- src/login/login.component.tsx
A refined UI for the login app. Still using emotion css (and pixels :-)) temporarily. Also, currently not responsive.
> Refined UI

- src/login/login.component.tsx
- src/root.component.tsx
Patient dashboard probably isn't the route we'll end up redirecting to in the long term, but for the upcoming hackathon that is where we are going to redirect to.
> Redirecting to patient dashboard after successful login.

- .babelrc
- package-lock.json
- package.json
- src/login.tsx
- src/root.component.tsx
Implementing componentDidCatch, to remove console warning. Read more at https://github.com/CanopyTax/single-spa-react#notes
> Implementing componentDidCatch

- src/login/login.component.tsx
See https://issues.openmrs.org/projects/MF/issues/MF-17 and https://styleguide.openmrs.org/?path=/story/openmrs-styleguide--cards
> Switching login page to use styleguide card.

- .eslintrc
- package-lock.json
- package.json
- src/login/login.component.tsx
See related https://issues.openmrs.org/browse/MF-22
> MF-22: Switching login button to use styleguide button.

- .eslintignore
- __mocks__/openmrs-esm-api.mock.tsx
- jest.config.json
- src/login/login.resource.tsx
- src/openmrs-esm-login.d.tsx
- webpack.config.js
See related https://issues.openmrs.org/projects/MF/issues/MF-22?filter=allopenissues
> MF-22: Switching to using openmrsFetch

- src/login/login.component.tsx
See https://issues.openmrs.org/browse/MF-22
> MF-22: Implementing toggling password visibility

- src/login/login.component.tsx
See https://issues.openmrs.org/projects/MF/issues/MF-19
> MF-19: Switching to styleguide's OpenMRS logo

- package-lock.json
- package.json
- src/root.component.tsx
- webpack.config.js
https://issues.openmrs.org/browse/MF-43
> Switch login esm react projects to use @openmrs/react-root-decorator

- .travis.yml
- package-lock.json
On Deployment Success
On Deployment Error
> MF-42: Make travis build fail if deployment fails

- __mocks__/openmrs-esm-api.mock.tsx
- package-lock.json
- package.json
- src/login/login.component.tsx
- src/openmrs-esm-login.d.tsx
If you're already logged in, you shouldn't be shown the login page.
> Redirecting to home page if user is already logged in.

- package-lock.json
- package.json
See openmrs/packmap#1 and MF-58
> Fixing dependencies for packmap packaging.

- src/login/login.component.tsx
- src/root.component.tsx
https://issues.openmrs.org/projects/MF/issues/MF-88
> MF-88 Login ESM should get login button target URL from config

- __mocks__/openmrs-esm-error-handling.mock.tsx
- __mocks__/openmrs-esm-module-config.mock.tsx
- jest.config.json
- package-lock.json
- package.json
- src/choose-location/choose-location.component.test.tsx
- src/choose-location/choose-location.component.tsx
- src/choose-location/choose-location.resource.ts
- src/login/login.component.test.tsx
- src/login/login.component.tsx
- src/openmrs-backend-dependencies.ts
- src/root.component.tsx
- src/styles.css
- translations/en.json
https://issues.openmrs.org/browse/MF-109
> MF-109  Login flow should have Location select as second page

- src/choose-location/choose-location.component.tsx
> Adding location radio button styles

- package-lock.json
- src/choose-location/choose-location.component.tsx
- src/styles.css
- translations/en.json
@brandones .  Wanted to get this committed into a branch and up for review (code and design).  It just has CSS changes and I also threw in a basic display of the username for now.  Looks like this:
> Styled radios

- src/styles.css
> Fixed location radio button position

- src/choose-location/choose-location.component.tsx
- src/styles.css
> Support multiple columns of locations

- src/choose-location/choose-location.component.tsx
- src/login/login.component.tsx
- src/navigate.ts
This is causing an issue where a PIH config does not work on some servers (e.g. humci) because those servers have a different base path from `/openmrs`.
> Non-spa redirect URLs should be relative to window.openmrsBase

- src/choose-location/choose-location.component.tsx
- src/styles.css
https://issues.openmrs.org/browse/MF-181
Upon logging in, the welcome message at the top of the page should display the logged-in user's username as part of the greeting.
> MF-181: Welcome message not displaying username after logging in

- translations/en.json
> Add missing i18n key for Welcome

- src/choose-location/choose-location.component.tsx
- src/login/login.component.tsx
> Use optional chaining 😌

- package-lock.json
- src/choose-location/choose-location.component.test.tsx
- src/choose-location/choose-location.component.tsx
- src/choose-location/choose-location.resource.ts
- src/root.component.tsx
- translations/en.json
https://issues.openmrs.org/browse/MF-114
The feature adds a searchbox that allows users to input the name of a location and confirm selection to proceed to user dashboard. This feature uses FHIR2 Location resource
> Add location/facility search box

- src/styles.css
Added small margin top for the login card to give better look for the card layout.
Before Change:
After Change:
> Added margin top for the login card

- package-lock.json
- package.json
- src/choose-location/choose-location.resource.ts
This is why openmrs-spa location chooser is broken
> Update to esm-api 3.0

- .travis.yml
- package-lock.json
- package.json
- src/choose-location/choose-location.component.tsx
- src/index.ts
- src/login/login.component.tsx
- src/openmrs-esm-login.tsx
- src/set-public-path.ts
- webpack.config.js
Refactored to use `decentralized-activation`.
**Important**:
The module name has to be renamed with a suffix of `-app`. As outlined last week we should also rename the repository then.
> Decentralized Activation

- src/location-picker/location-picker.component.test.tsx
- src/location-picker/location-picker.component.tsx
Ticket [MF-278](https://issues.openmrs.org/browse/MF-278)
> MF-278: Autofocus search input on location picker component

- src/index.ts
- src/location-picker-parcel.component.tsx
- src/location-picker/location-picker.component.tsx
[MF-265](https://issues.openmrs.org/projects/MF/issues/MF-265?filter=allissues)
> MF-265 UI for User to change their location

- src/location-picker/location-picker.component.test.tsx
- src/location-picker/location-picker.component.tsx
This PR fixes [MF-256](https://issues.openmrs.org/projects/MF/issues/MF-256?filter=allissues)
> MF:256: Fixed location widget not to retain selection after search

- src/location-picker/location-picker.component.test.tsx
- src/location-picker/location-picker.component.tsx
This PR resolves this ticket [MF-115](https://issues.openmrs.org/projects/MF/issues/MF-115?filter=allissuesl)
> MF-115:Location/facility selectors should default to the last used by user

- jest.config.json
- package-lock.json
- package.json
- src/declarations.d.tsx
- src/location-picker/location-picker.component.scss
- src/location-picker/location-picker.component.tsx
- src/login/login.component.test.tsx
- src/login/login.component.tsx
- src/root.scss
- src/setup-tests.js
- src/styles.scss
- translations/en.json
- translations/es.json
- webpack.config.js
Update the login screen to match the latest designs
https://app.zeplin.io/project/5f7223cfda10f94d67cec6d0/screen/601827beb2ba880451a7ee44
﻿
> Update to match latest designs

- src/login/login.component.tsx
> Omit unnecessary space between help text and question mark

- package-lock.json
- src/change-location-link/change-location-link.component.test.tsx
- src/change-location-link/change-location-link.component.tsx
- src/change-location-link/change-location-link.resource.ts
- src/change-location-link/change-location.link.component.scss
- src/choose-location/choose-location.component.test.tsx
- src/choose-location/choose-location.component.tsx
- src/index.ts
- src/location-picker/location-picker.component.test.tsx
- src/location-picker/location-picker.component.tsx
- src/root.scss
- src/styles.scss
[MF-435](https://issues.openmrs.org/browse/MF-435)
Linked to this [PR](https://github.com/openmrs/openmrs-esm-primary-navigation/pull/52)
1. Define a change-location link as an extension used to change location
[GIF Screenshoot](https://user-images.githubusercontent.com/28008754/109044214-309a3b80-76e3-11eb-93fe-338e5d33f0bf.gif)
>  MF-435 : Move location selection under user profile

- package-lock.json
- src/change-location-link/change-location-link.component.tsx
- src/change-location-link/change-location.link.component.scss
- src/index.ts
- src/root.scss
1. Add location changer as an extension
> MF-435: Add location changer as an extension

- package-lock.json
- src/choose-location/choose-location.resource.ts
See ticket for details: https://issues.openmrs.org/browse/MF-510
> MF-510: Replace AppUI endpoints with webservices.rest's

- .editorconfig
- package-lock.json
- package.json
- prettier.config.js
- src/CurrentUserContext.tsx
- src/change-location-link/change-location-link.component.test.tsx
- src/change-location-link/change-location-link.component.tsx
- src/choose-location/choose-location.component.test.tsx
- src/choose-location/choose-location.component.tsx
- src/choose-location/choose-location.resource.ts
- src/config-schema.ts
- src/declarations.d.tsx
- src/index.ts
- src/loading/loading.component.tsx
- src/location-picker/location-picker.component.test.tsx
- src/location-picker/location-picker.component.tsx
- src/login/login.component.test.tsx
- src/login/login.component.tsx
- src/login/login.resource.tsx
- src/openmrs-backend-dependencies.ts
- src/root.component.test.tsx
- src/root.component.tsx
- src/set-public-path.ts
- src/setup-tests.js
- src/test-helpers/render-with-router.tsx
- src/types.ts
The repository was missing the `.editorconfig` and prettier configuration files which made any commit on my machine fail due styling issues found in the pre-commit hook.
I simply copied the files/config from the patient-registration repo here.
**⚠ Feel free to abandon this PR if these changes are undesired or if they come at a bad time (e.g. due to merge conflicts with other open PRs).**
> Added .editorconfig and added/ran prettier.

- package-lock.json
- package.json
- src/choose-location/choose-location.component.test.tsx
- src/choose-location/choose-location.component.tsx
- src/index.ts
- src/location-picker/location-picker.component.test.tsx
- src/location-picker/location-picker.component.tsx
- src/login/login.component.test.tsx
- src/login/login.component.tsx
- src/root.component.test.tsx
- src/root.component.tsx
- translations/en.json
- webpack.config.js
Makes the login MF able to render offline.
While it can render and redirect appropriately, the login/change location buttons are disabled when both offline and signed out.
> MF-556: Introduce Offline Setup Function in Login
